import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/Footer'
import { Providers } from '@/components/Providers'




export const metadata: Metadata = {
  title: ' Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen flex flex-col' >
        <Providers>
          <Header />
          <main className='flex-grow'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
